#!/usr/bin/env node
// Regenerates sitemap.xml from the declared set of public pages.
//
// WHY THIS IS A SCRIPT AND NOT A HAND-WRITTEN FILE
// -----------------------------------------------
// A sitemap's <lastmod> is only worth having if it is true. Typed by hand
// it is right on the day it is written and a lie every day after, and a
// lastmod that never matches the page teaches Google to ignore the field.
// So the date is never authored here: it is read from git, the one record
// of when each page actually changed.
//
// Run it after changing any public page:
//
//   node scripts/generate-sitemap.mjs
//
// and commit the result. `node scripts/ci-checks.js` (check 13) then
// validates the committed file on every push.
//
// WHY CI REGENERATES NOTHING
// --------------------------
// actions/checkout@v4 makes a depth-1 clone. `git log` there reports the
// single fetched commit for every file, so dates computed in CI would be
// uniformly wrong. CI therefore checks the sitemap's invariants -- which
// need no history -- and leaves generation to a full checkout.

import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const { findXmlErrors, xmlComment } = createRequire(import.meta.url)('./xml-wellformed.cjs');

const ROOT = path.join(path.dirname(new URL(import.meta.url).pathname), '..');
const ORIGIN = 'https://www.darweshgroup.com';

// The public, canonical, crawlable set -- decided by reading each page,
// not by listing *.html. Every other page in the repository is excluded
// for a stated reason; scripts/ci-checks.js check 13 holds the full
// classification and fails if a new page is left unclassified.
//
// `priority` and `changefreq` are deliberately absent. Google has said
// publicly that it ignores both, and inventing numbers for them would be
// exactly the kind of decorative precision this file exists to avoid.
const PUBLIC_PAGES = [
  { file: 'index.html', loc: '/' },
  { file: 'about.html', loc: '/about.html' },
  { file: 'buy.html', loc: '/buy.html' },
  { file: 'rent.html', loc: '/rent.html' },
  { file: 'sell.html', loc: '/sell.html' },
  { file: 'map.html', loc: '/map.html' },
  { file: 'services.html', loc: '/services.html' },
  { file: 'projects.html', loc: '/projects.html' },
  { file: 'installments.html', loc: '/installments.html' },
  { file: 'insights.html', loc: '/insights.html' },
  { file: 'build.html', loc: '/build.html' },
  { file: 'renovate.html', loc: '/renovate.html' },
  { file: 'design.html', loc: '/design.html' },
  { file: 'mam-ai.html', loc: '/mam-ai.html' },
];

/** The page's own last commit date (YYYY-MM-DD), or null in a shallow or
 *  missing checkout -- in which case the entry ships with no <lastmod>
 *  rather than a guessed one. */
function lastCommitDate(file) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : null;
  } catch {
    return null;
  }
}

const entries = PUBLIC_PAGES.map(({ file, loc }) => {
  const abs = path.join(ROOT, file);
  if (!fs.existsSync(abs)) {
    console.error(`generate-sitemap: ${file} is listed as public but does not exist`);
    process.exit(1);
  }
  // The sitemap URL and the page's own canonical must be the same string.
  // If they disagree, one of them is wrong and it is not this script's
  // place to pick a winner.
  const html = fs.readFileSync(abs, 'utf8');
  const canonical = (html.match(/<link rel="canonical" href="([^"]+)"/) || [])[1];
  const expected = ORIGIN + loc;
  if (canonical !== expected) {
    console.error(
      `generate-sitemap: ${file} declares canonical "${canonical}" but the sitemap would list "${expected}". `
      + 'Fix the page or this list -- do not ship a sitemap that disagrees with the page.',
    );
    process.exit(1);
  }
  return { loc: expected, lastmod: lastCommitDate(file) };
});

const missing = entries.filter((e) => !e.lastmod).length;
if (missing) {
  console.warn(
    `generate-sitemap: ${missing} page(s) have no resolvable git date (shallow clone?); `
    + 'they are written without <lastmod> rather than with an invented one.',
  );
}

// The comment is BUILT, never interpolated raw. An earlier version of this
// file wrote "generate-sitemap.mjs -- do not edit by hand" straight into
// the template; XML forbids "--" inside a comment, so every parser rejected
// the whole document and the live sitemap contained zero usable URLs.
// xmlComment() collapses hyphen runs, which makes that class of mistake
// unreachable no matter how the wording below is later edited.
const header = xmlComment([
  '  Generated by scripts/generate-sitemap.mjs - do not edit by hand.',
  "  Every lastmod is the page's own last commit date, read from git.",
  '  Only public, canonical, crawlable pages appear here: admin, account,',
  '  authentication and parameter-driven detail templates are excluded.',
].join('\n'));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
${header}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map(({ loc, lastmod }) => (
    lastmod
      ? `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`
      : `  <url>\n    <loc>${loc}</loc>\n  </url>`
  )).join('\n')}
</urlset>
`;

// Belt and braces: sanitizing the input should make this impossible, but a
// malformed sitemap must never reach disk, let alone production. Checking
// the bytes about to be written is the only assertion that cannot be
// fooled by a bug in the construction above.
const errors = findXmlErrors(xml);
if (errors.length) {
  console.error('generate-sitemap: refusing to write malformed XML:');
  errors.forEach((e) => console.error(`  line ${e.line}, column ${e.column}: ${e.message}`));
  process.exit(1);
}

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml);
console.log(`sitemap.xml written: ${entries.length} public URLs, XML well-formed`);
